---
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-primary:8010/eureka,http://eureka-secondary:8012/eureka/,http://eureka-tertiary:8013/eureka/
  instance:
      instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}     
---
spring:
  profiles: ESSubject
words: I,You,He,She,It

---
spring:
  profiles: ESVerb
words: ran,knew,had,saw,bought

---
spring:
  profiles: ESArticle
words: a,the

---
spring:
  profiles: ESAdjective
words: reasonable,leaky,suspicious,ordinary,unlikely

---
spring:
  profiles: ESNoun
words: boat,book,vote,seat,backpack,partition,groundhog 
