---
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-primary:8010/eureka,http://eureka-secondary:8012/eureka/,http://eureka-tertiary:8013/eureka/
  instance:
      instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}     
  
# Tell Spring Boot Actuator to expose the hystrix.stream endpoint.
# This is listened to by the Hystrix dashboard for monitoring purposes:
management: 
  endpoints: 
    web: 
      exposure: 
        include: health,info,bus-refresh,'hystrix.stream'
---
spring:
  profiles: ESSubject
  application:
    name: ESSubject
words: I,You,He,She,It

---
spring:
  profiles: ESVerb
  application:
    name: ESVerb
words: ran,knew,had,saw,bought

---
spring:
  profiles: ESArticle
  application:
    name: ESArticle
words: a,the

---
spring:
  profiles: ESAdjective
  application:
    name: ESAdjective
words: reasonable,leaky,suspicious,ordinary,unlikely

---
spring:
  profiles: ESNoun
  application:
    name: ESNoun
words: boat,book,vote,seat,backpack,partition,groundhog 

---
words: fallback
---
spring:
  profiles: cold-noun
  application:
    name: ESNoun
words: icicle,refrigerator,blizzard,snowball
---
spring:
  application:
    name: BusServer
